# Linear Regression

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [ ]:
model = LinearRegression().fit(x, y)
model

In [10]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)
print("intercept:", model.intercept_)
print("slope:", model.coef_)

coefficient of determination: 0.715875613747954
intercept: 5.633333333333333
slope: [0.54]


In [11]:
y_pred = model.predict(x)
print("predicted response: ", y_pred, sep="\n")

predicted response: 
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


# Multiple Linear Regression

In [13]:
x = [
    [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
x, y

(array([[ 0,  1],
        [ 5,  1],
        [15,  2],
        [25,  5],
        [35, 11],
        [45, 15],
        [55, 34],
        [60, 35]]),
 array([ 4,  5, 20, 14, 32, 22, 38, 43]))

In [14]:
model = LinearRegression().fit(x, y)

In [15]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)
print("intercept:", model.intercept_)
print("slope:", model.coef_)

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


In [17]:
y_pred = model.predict(x)
print("predicted response: ", y_pred, sep="\n")

predicted response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


# Polynomial Regression

In [19]:
from sklearn.preprocessing import PolynomialFeatures

In [20]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [25]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [27]:
model = LinearRegression().fit(x_, y)
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print("intercept:", model.intercept_)
print("coefficients:", model.coef_)

coefficient of determination: 0.8908516262498564
intercept: 21.37232142857143
coefficients: [-1.32357143  0.02839286]


In [30]:
y_pred = model.predict(x_)
print("predicted response: ", y_pred)

predicted response:  [15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
